import { LightningQuestion } from "../../types";

export const MATH_QUESTIONS: LightningQuestion[] = [
  {
    id: "lt-math-1",
    category: "Mathematics",
    questionType: "mcq",
    difficulty: "Easy",
    question: "What is 7 × 8?",
    options: ["54", "56", "62", "64"],
    correctIndex: 1,
  },
  {
    id: "lt-math-2",
    category: "Mathematics",
    questionType: "true_false",
    difficulty: "Easy",
    question: "The square root of 64 is 8.",
    options: ["True", "False"],
    correctIndex: 0,
  },
  {
    id: "lt-math-3",
    category: "Mathematics",
    questionType: "mcq",
    difficulty: "Medium",
    question: "What is 15% of 300?",
    options: ["35", "40", "45", "50"],
    correctIndex: 2,
  },
  {
    id: "lt-math-4",
    category: "Mathematics",
    questionType: "true_false",
    difficulty: "Easy",
    question: "2 is the only even prime number.",
    options: ["True", "False"],
    correctIndex: 0,
  },
  {
    id: "lt-math-5",
    category: "Mathematics",
    questionType: "mcq",
    difficulty: "Hard",
    question: "Solve for x: 3x - 7 = 14",
    options: ["5", "6", "7", "8"],
    correctIndex: 2,
  },
  {
    id: "lt-math-6",
    category: "Mathematics",
    questionType: "mcq",
    difficulty: "Easy",
    question: "What is 2⁵?",
    options: ["16", "25", "32", "64"],
    correctIndex: 2,
  },
  {
    id: "lt-math-7",
    category: "Mathematics",
    questionType: "true_false",
    difficulty: "Medium",
    question: "The sum of angles in a quadrilateral is 360°.",
    options: ["True", "False"],
    correctIndex: 0,
  },
  {
    id: "lt-math-8",
    category: "Mathematics",
    questionType: "mcq",
    difficulty: "Medium",
    question: "LCM of 6 and 8 is:",
    options: ["14", "24", "32", "48"],
    correctIndex: 1,
  },
  {
    id: "lt-math-9",
    category: "Mathematics",
    questionType: "true_false",
    difficulty: "Hard",
    question: "0! (zero factorial) equals 0.",
    options: ["True", "False"],
    correctIndex: 1,
  },
  {
    id: "lt-math-10",
    category: "Mathematics",
    questionType: "mcq",
    difficulty: "Easy",
    question: "What is 100 ÷ 4?",
    options: ["20", "25", "30", "40"],
    correctIndex: 1,
  },
  {
    id: "lt-math-11",
    category: "Mathematics",
    questionType: "mcq",
    difficulty: "Medium",
    question: "Perimeter of a square with side length 9 cm:",
    options: ["18 cm", "27 cm", "36 cm", "81 cm"],
    correctIndex: 2,
  },
  {
    id: "lt-math-12",
    category: "Mathematics",
    questionType: "true_false",
    difficulty: "Easy",
    question: "A heptagon has 7 sides.",
    options: ["True", "False"],
    correctIndex: 0,
  },
];
