import { LightningQuestion } from "../../types";

export const SCIENCE_QUESTIONS: LightningQuestion[] = [
  {
    id: "lt-sci-1",
    category: "Science",
    questionType: "mcq",
    difficulty: "Easy",
    question: "What chemical symbol represents Sodium?",
    options: ["So", "Na", "Sd", "K"],
    correctIndex: 1,
  },
  {
    id: "lt-sci-2",
    category: "Science",
    questionType: "true_false",
    difficulty: "Easy",
    question: "Sound travels faster through air than through water.",
    options: ["True", "False"],
    correctIndex: 1,
  },
  {
    id: "lt-sci-3",
    category: "Science",
    questionType: "mcq",
    difficulty: "Medium",
    question: "What is the pH value of pure water at room temperature?",
    options: ["0", "5", "7", "14"],
    correctIndex: 2,
  },
  {
    id: "lt-sci-4",
    category: "Science",
    questionType: "true_false",
    difficulty: "Medium",
    question: "Light travels in straight lines.",
    options: ["True", "False"],
    correctIndex: 0,
  },
  {
    id: "lt-sci-5",
    category: "Science",
    questionType: "mcq",
    difficulty: "Hard",
    question: "SI unit of electrical resistance:",
    options: ["Volt", "Ampere", "Ohm", "Watt"],
    correctIndex: 2,
  },
  {
    id: "lt-sci-6",
    category: "Science",
    questionType: "mcq",
    difficulty: "Easy",
    question: "Which gas is required for photosynthesis?",
    options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"],
    correctIndex: 1,
  },
  {
    id: "lt-sci-7",
    category: "Science",
    questionType: "true_false",
    difficulty: "Hard",
    question: "Electrons carry a positive electric charge.",
    options: ["True", "False"],
    correctIndex: 1,
  },
  {
    id: "lt-sci-8",
    category: "Science",
    questionType: "mcq",
    difficulty: "Medium",
    question: "Standard acceleration due to Earth's gravity (g):",
    options: ["7.8 m/s²", "9.8 m/s²", "11.2 m/s²", "12.0 m/s²"],
    correctIndex: 1,
  },
  {
    id: "lt-sci-9",
    category: "Science",
    questionType: "true_false",
    difficulty: "Easy",
    question: "Water boils at 100°C at standard atmospheric pressure.",
    options: ["True", "False"],
    correctIndex: 0,
  },
];
