import { ReviewPayload } from "../types";

export const MOCK_REVIEW_DATA: ReviewPayload = {
  subjectName: "General Science",
  trackName: "Explorer Track",
  trackType: "explorer",
  title: "Thermodynamics & Fundamental Physics — Practice Set 1",
  totalQuestions: 5,
  correctCount: 4,
  incorrectCount: 1,
  skippedCount: 0,
  accuracyPercent: 80,
  questions: [
    {
      id: "rev-q1",
      number: 1,
      typeLabel: "Multiple Choice",
      prompt: "Which law of thermodynamics defines the concept of absolute temperature and zero entropy at absolute zero?",
      status: "correct",
      studentAnswer: "Third Law of Thermodynamics",
      correctAnswer: "Third Law of Thermodynamics",
      explanation: "The Third Law of Thermodynamics states that the entropy of a perfect crystal approaches zero as the absolute temperature approaches zero Kelvin (0 K).",
    },
    {
      id: "rev-q2",
      number: 2,
      typeLabel: "True / False",
      prompt: "In an isothermal process for an ideal gas, the total internal energy remains constant throughout the transition.",
      status: "correct",
      studentAnswer: "TRUE",
      correctAnswer: "TRUE",
      explanation: "For an ideal gas, internal energy (U) depends solely on temperature (T). Since temperature remains constant (ΔT = 0) in an isothermal process, the change in internal energy (ΔU) is zero.",
    },
    {
      id: "rev-q3",
      number: 3,
      typeLabel: "Match the Following",
      prompt: "Match each thermodynamic process in Column A with its defining mathematical condition in Column B.",
      status: "incorrect",
      studentAnswer: "Isothermal: Volume = Constant, Isochoric: Temperature = Constant",
      correctAnswer: "Isothermal: Temperature = Constant, Isochoric: Volume = Constant, Isobaric: Pressure = Constant, Adiabatic: Heat = 0",
      explanation: "Isothermal indicates constant temperature (T=const), Isochoric indicates constant volume (V=const), Isobaric indicates constant pressure (P=const), and Adiabatic indicates zero heat exchange (Q=0).",
    },
    {
      id: "rev-q4",
      number: 4,
      typeLabel: "Fill in the Blank",
      prompt: "The SI unit of specific heat capacity is ________ per kilogram per Kelvin.",
      status: "correct",
      studentAnswer: "Joules",
      correctAnswer: "Joules",
      explanation: "Specific heat capacity is measured in Joules per kilogram per Kelvin (J/(kg·K)) or J·kg⁻¹·K⁻¹ in SI units.",
    },
    {
      id: "rev-q5",
      number: 5,
      typeLabel: "Multiple Choice",
      prompt: "What is the maximum theoretical efficiency limit for any heat engine operating between two thermal reservoirs governed by?",
      status: "correct",
      studentAnswer: "Carnot Efficiency Limit",
      correctAnswer: "Carnot Efficiency Limit",
      explanation: "The Carnot theorem establishes that no heat engine operating between two thermal reservoirs can be more efficient than a Carnot engine operating between those same reservoirs.",
    },
  ],
};
