import { MatchPair } from "../types";

export const MOCK_MATCH_PAIRS: MatchPair[] = [
  // Science & Biology (15)
  { id: "mp-sci-1", category: "Science", itemA: "Heart", itemB: "Pumps Blood" },
  { id: "mp-sci-2", category: "Science", itemA: "Neuron", itemB: "Brain Cell" },
  { id: "mp-sci-3", category: "Science", itemA: "Photosynthesis", itemB: "Plant Food Process" },
  { id: "mp-sci-4", category: "Science", itemA: "Mitochondria", itemB: "Powerhouse of Cell" },
  { id: "mp-sci-5", category: "Science", itemA: "Chlorophyll", itemB: "Green Pigment" },
  { id: "mp-sci-6", category: "Science", itemA: "H₂O", itemB: "Water" },
  { id: "mp-sci-7", category: "Science", itemA: "NaCl", itemB: "Table Salt" },
  { id: "mp-sci-8", category: "Science", itemA: "CO₂", itemB: "Carbon Dioxide" },
  { id: "mp-sci-9", category: "Science", itemA: "O₂", itemB: "Oxygen Gas" },
  { id: "mp-sci-10", category: "Science", itemA: "Hydrochloric Acid", itemB: "Stomach Acid (HCl)" },
  { id: "mp-sci-11", category: "Science", itemA: "Gravity", itemB: "9.8 m/s² Acceleration" },
  { id: "mp-sci-12", category: "Science", itemA: "Ohm (Ω)", itemB: "Electric Resistance" },
  { id: "mp-sci-13", category: "Science", itemA: "Ampere (A)", itemB: "Electric Current" },
  { id: "mp-sci-14", category: "Science", itemA: "Red Blood Cells", itemB: "Transports Oxygen" },
  { id: "mp-sci-15", category: "Science", itemA: "White Blood Cells", itemB: "Immune Defense" },

  // Mathematics (15)
  { id: "mp-math-1", category: "Mathematics", itemA: "Square Root of 144", itemB: "12" },
  { id: "mp-math-2", category: "Mathematics", itemA: "Triangle Interior Angles", itemB: "180° Sum" },
  { id: "mp-math-3", category: "Mathematics", itemA: "Circle Area Formula", itemB: "πr²" },
  { id: "mp-math-4", category: "Mathematics", itemA: "Right Angle", itemB: "90°" },
  { id: "mp-math-5", category: "Mathematics", itemA: "3³ (3 Cubed)", itemB: "27" },
  { id: "mp-math-6", category: "Mathematics", itemA: "15% of 200", itemB: "30" },
  { id: "mp-math-7", category: "Mathematics", itemA: "Prime Number", itemB: "7" },
  { id: "mp-math-8", category: "Mathematics", itemA: "0! (Factorial 0)", itemB: "1" },
  { id: "mp-math-9", category: "Mathematics", itemA: "Hypotenuse (6, 8)", itemB: "10" },
  { id: "mp-math-10", category: "Mathematics", itemA: "LCM of 4 and 6", itemB: "12" },
  { id: "mp-math-11", category: "Mathematics", itemA: "Perimeter of Square", itemB: "4 × side" },
  { id: "mp-math-12", category: "Mathematics", itemA: "Quadrilateral Angles", itemB: "360° Sum" },
  { id: "mp-math-13", category: "Mathematics", itemA: "Even Prime Number", itemB: "2" },
  { id: "mp-math-14", category: "Mathematics", itemA: "Reciprocal of 4", itemB: "1/4" },
  { id: "mp-math-15", category: "Mathematics", itemA: "Hexagon Sides", itemB: "6 Sides" },

  // Geography & Countries (15)
  { id: "mp-geo-1", category: "Geography", itemA: "Capital of India", itemB: "New Delhi" },
  { id: "mp-geo-2", category: "Geography", itemA: "Capital of Japan", itemB: "Tokyo" },
  { id: "mp-geo-3", category: "Geography", itemA: "Capital of France", itemB: "Paris" },
  { id: "mp-geo-4", category: "Geography", itemA: "Capital of UK", itemB: "London" },
  { id: "mp-geo-5", category: "Geography", itemA: "Capital of Karnataka", itemB: "Bengaluru" },
  { id: "mp-geo-6", category: "Geography", itemA: "Longest River", itemB: "Nile River" },
  { id: "mp-geo-7", category: "Geography", itemA: "Highest Mountain Peak", itemB: "Mount Everest" },
  { id: "mp-geo-8", category: "Geography", itemA: "Largest Ocean", itemB: "Pacific Ocean" },
  { id: "mp-geo-9", category: "Geography", itemA: "Hot Desert in Africa", itemB: "Sahara Desert" },
  { id: "mp-geo-10", category: "Geography", itemA: "Red Planet", itemB: "Mars" },
  { id: "mp-geo-11", category: "Geography", itemA: "Largest Island Country", itemB: "Indonesia" },
  { id: "mp-geo-12", category: "Geography", itemA: "Equator Latitude", itemB: "0° Latitude" },
  { id: "mp-geo-13", category: "Geography", itemA: "Prime Meridian", itemB: "0° Longitude" },
  { id: "mp-geo-14", category: "Geography", itemA: "Regur Soil", itemB: "Black Cotton Soil" },
  { id: "mp-geo-15", category: "Geography", itemA: "Roof of the World", itemB: "Pamir Plateau" },

  // Computer Science (12)
  { id: "mp-cs-1", category: "Computer Science", itemA: "CPU", itemB: "Central Processing Unit" },
  { id: "mp-cs-2", category: "Computer Science", itemA: "RAM", itemB: "Random Access Memory" },
  { id: "mp-cs-3", category: "Computer Science", itemA: "HTML", itemB: "HyperText Markup Language" },
  { id: "mp-cs-4", category: "Computer Science", itemA: "Binary System", itemB: "Base-2 (0 and 1)" },
  { id: "mp-cs-5", category: "Computer Science", itemA: "World Wide Web Creator", itemB: "Tim Berners-Lee" },
  { id: "mp-cs-6", category: "Computer Science", itemA: "1 Byte", itemB: "8 Bits" },
  { id: "mp-cs-7", category: "Computer Science", itemA: "GPU", itemB: "Graphics Processing Unit" },
  { id: "mp-cs-8", category: "Computer Science", itemA: "SSD", itemB: "Solid State Drive" },
  { id: "mp-cs-9", category: "Computer Science", itemA: "IP Address", itemB: "Internet Protocol" },
  { id: "mp-cs-10", category: "Computer Science", itemA: "Algorithm", itemB: "Step-by-Step Instructions" },
  { id: "mp-cs-11", category: "Computer Science", itemA: "Compiler", itemB: "Translates Code to Machine" },
  { id: "mp-cs-12", category: "Computer Science", itemA: "1 Kilobyte", itemB: "1024 Bytes" },

  // English Vocabulary (15)
  { id: "mp-eng-1", category: "English", itemA: "Meticulous", itemB: "Extremely Careful" },
  { id: "mp-eng-2", category: "English", itemA: "Opaque", itemB: "Not Transparent" },
  { id: "mp-eng-3", category: "English", itemA: "Benevolent", itemB: "Kind & Generous" },
  { id: "mp-eng-4", category: "English", itemA: "Gigantic", itemB: "Enormous / Huge" },
  { id: "mp-eng-5", category: "English", itemA: "Rapid", itemB: "Very Fast" },
  { id: "mp-eng-6", category: "English", itemA: "Personification", itemB: "Human Qualities to Non-human" },
  { id: "mp-eng-7", category: "English", itemA: "Bite the Bullet", itemB: "Face Difficulty Bravely" },
  { id: "mp-eng-8", category: "English", itemA: "Portmanteau", itemB: "Blended Word (e.g. Smog)" },
  { id: "mp-eng-9", category: "English", itemA: "Happiness", itemB: "Abstract Noun" },
  { id: "mp-eng-10", category: "English", itemA: "Write Past Participle", itemB: "Written" },
  { id: "mp-eng-11", category: "English", itemA: "Candid", itemB: "Frank and Honest" },
  { id: "mp-eng-12", category: "English", itemA: "Antonym of Ancient", itemB: "Modern" },
  { id: "mp-eng-13", category: "English", itemA: "Simile Marker", itemB: "Uses 'Like' or 'As'" },
  { id: "mp-eng-14", category: "English", itemA: "Metaphor", itemB: "Direct Comparison" },
  { id: "mp-eng-15", category: "English", itemA: "Abundant", itemB: "Plentiful" },

  // History & Civics (15)
  { id: "mp-his-1", category: "History", itemA: "Father of Indian Constitution", itemB: "Dr. B.R. Ambedkar" },
  { id: "mp-his-2", category: "History", itemA: "Dandi March Year", itemB: "1930" },
  { id: "mp-his-3", category: "History", itemA: "Indian Independence Year", itemB: "1947" },
  { id: "mp-his-4", category: "History", itemA: "Democracy", itemB: "Government by the People" },
  { id: "mp-his-5", category: "History", itemA: "UN Security Council", itemB: "Peace & Security" },
  { id: "mp-his-6", category: "History", itemA: "First World War Begin", itemB: "1914" },
  { id: "mp-his-7", category: "History", itemA: "Industrial Revolution Origin", itemB: "Great Britain" },
  { id: "mp-his-8", category: "History", itemA: "Article 32 Indian Constitution", itemB: "Heart & Soul" },
  { id: "mp-his-9", category: "History", itemA: "Magna Carta Year", itemB: "1215" },
  { id: "mp-his-10", category: "History", itemA: "Mona Lisa Painter", itemB: "Leonardo da Vinci" },
  { id: "mp-his-11", category: "History", itemA: "Sardar Vallabhbhai Patel", itemB: "Iron Man of India" },
  { id: "mp-his-12", category: "History", itemA: "Quit India Movement", itemB: "1942" },
  { id: "mp-his-13", category: "History", itemA: "French Revolution Year", itemB: "1789" },
  { id: "mp-his-14", category: "History", itemA: "Ashoka's Empire", itemB: "Maurya Dynasty" },
  { id: "mp-his-15", category: "History", itemA: "Preamble First Word", itemB: "We, the People" },

  // General Knowledge & Animals (15)
  { id: "mp-gk-1", category: "General Knowledge", itemA: "National Animal of India", itemB: "Royal Bengal Tiger" },
  { id: "mp-gk-2", category: "General Knowledge", itemA: "Currency of Japan", itemB: "Japanese Yen (¥)" },
  { id: "mp-gk-3", category: "General Knowledge", itemA: "Heptagon", itemB: "7-Sided Polygon" },
  { id: "mp-gk-4", category: "General Knowledge", itemA: "Hardest Natural Mineral", itemB: "Diamond" },
  { id: "mp-gk-5", category: "General Knowledge", itemA: "Barometer", itemB: "Measures Air Pressure" },
  { id: "mp-gk-6", category: "General Knowledge", itemA: "Thermometer", itemB: "Measures Temperature" },
  { id: "mp-gk-7", category: "General Knowledge", itemA: "Speed of Light", itemB: "3 × 10⁸ m/s" },
  { id: "mp-gk-8", category: "General Knowledge", itemA: "Largest Mammal", itemB: "Blue Whale" },
  { id: "mp-gk-9", category: "General Knowledge", itemA: "Fastest Land Animal", itemB: "Cheetah" },
  { id: "mp-gk-10", category: "General Knowledge", itemA: "Universal Solvent", itemB: "Water" },
  { id: "mp-gk-11", category: "General Knowledge", itemA: "Smallest Bird", itemB: "Hummingbird" },
  { id: "mp-gk-12", category: "General Knowledge", itemA: "Solar System Central Star", itemB: "Sun" },
  { id: "mp-gk-13", category: "General Knowledge", itemA: "Dry Ice", itemB: "Solid Carbon Dioxide" },
  { id: "mp-gk-14", category: "General Knowledge", itemA: "Penicillin Discoverer", itemB: "Alexander Fleming" },
  { id: "mp-gk-15", category: "General Knowledge", itemA: "Light Year", itemB: "Unit of Astronomical Distance" },
];
