import { BrainBlitzQuestion } from "../types";

export const MOCK_BRAIN_BLITZ_QUESTIONS: BrainBlitzQuestion[] = [
  // Mathematics (10)
  {
    id: "q-math-1",
    category: "Mathematics",
    difficulty: "Easy",
    question: "What is the square root of 144?",
    options: ["10", "11", "12", "14"],
    correctIndex: 2,
    explanation: "12 × 12 = 144.",
  },
  {
    id: "q-math-2",
    category: "Mathematics",
    difficulty: "Easy",
    question: "What is the value of 3³?",
    options: ["9", "18", "27", "81"],
    correctIndex: 2,
    explanation: "3 × 3 × 3 = 27.",
  },
  {
    id: "q-math-3",
    category: "Mathematics",
    difficulty: "Medium",
    question: "If 2x + 5 = 15, what is x?",
    options: ["3", "4", "5", "10"],
    correctIndex: 2,
    explanation: "2x = 10 ⟹ x = 5.",
  },
  {
    id: "q-math-4",
    category: "Mathematics",
    difficulty: "Medium",
    question: "What is the sum of interior angles of a triangle?",
    options: ["90°", "180°", "270°", "360°"],
    correctIndex: 1,
    explanation: "The sum of interior angles of any Euclidean triangle is always 180°.",
  },
  {
    id: "q-math-5",
    category: "Mathematics",
    difficulty: "Hard",
    question: "What is the area of a circle with radius 7 cm? (π ≈ 22/7)",
    options: ["44 cm²", "98 cm²", "154 cm²", "308 cm²"],
    correctIndex: 2,
    explanation: "Area = πr² = (22/7) × 7 × 7 = 154 cm².",
  },
  {
    id: "q-math-6",
    category: "Mathematics",
    difficulty: "Easy",
    question: "What is 15% of 200?",
    options: ["20", "25", "30", "35"],
    correctIndex: 2,
    explanation: "15/100 × 200 = 30.",
  },
  {
    id: "q-math-7",
    category: "Mathematics",
    difficulty: "Medium",
    question: "What is the least common multiple (LCM) of 4 and 6?",
    options: ["12", "18", "24", "36"],
    correctIndex: 0,
    explanation: "Multiples of 4 are 4, 8, 12... and of 6 are 6, 12... Smallest common is 12.",
  },
  {
    id: "q-math-8",
    category: "Mathematics",
    difficulty: "Hard",
    question: "Find the hypotenuse of a right-angled triangle with sides 6 cm and 8 cm.",
    options: ["9 cm", "10 cm", "12 cm", "14 cm"],
    correctIndex: 1,
    explanation: "h² = 6² + 8² = 36 + 64 = 100 ⟹ h = 10 cm.",
  },
  {
    id: "q-math-9",
    category: "Mathematics",
    difficulty: "Easy",
    question: "What is the value of 0! (factorial of 0)?",
    options: ["0", "1", "Undefined", "Infinity"],
    correctIndex: 1,
    explanation: "By mathematical convention and definition, 0! = 1.",
  },
  {
    id: "q-math-10",
    category: "Mathematics",
    difficulty: "Medium",
    question: "The probability of rolling an even number on a standard 6-sided die is:",
    options: ["1/6", "1/3", "1/2", "2/3"],
    correctIndex: 2,
    explanation: "Even numbers on a die are {2, 4, 6} (3 outcomes out of 6) = 3/6 = 1/2.",
  },

  // Science (10)
  {
    id: "q-sci-1",
    category: "Science",
    difficulty: "Easy",
    question: "What chemical element does 'Na' represent?",
    options: ["Nickel", "Sodium", "Nitrogen", "Neon"],
    correctIndex: 1,
    explanation: "'Na' comes from the Latin word 'Natrium', representing Sodium.",
  },
  {
    id: "q-sci-2",
    category: "Science",
    difficulty: "Easy",
    question: "Which organelle is known as the powerhouse of the cell?",
    options: ["Ribosome", "Nucleus", "Mitochondria", "Golgi Body"],
    correctIndex: 2,
    explanation: "Mitochondria generate most of the chemical energy (ATP) needed by the cell.",
  },
  {
    id: "q-sci-3",
    category: "Science",
    difficulty: "Medium",
    question: "What is the pH value of pure water at 25°C?",
    options: ["5", "7", "9", "14"],
    correctIndex: 1,
    explanation: "Pure neutral water has a pH of 7.",
  },
  {
    id: "q-sci-4",
    category: "Science",
    difficulty: "Medium",
    question: "Which blood gas is primarily carried by hemoglobin?",
    options: ["Carbon Dioxide", "Oxygen", "Nitrogen", "Hydrogen"],
    correctIndex: 1,
    explanation: "Hemoglobin binds to oxygen in red blood cells to transport it from lungs to tissues.",
  },
  {
    id: "q-sci-5",
    category: "Science",
    difficulty: "Hard",
    question: "What is SI unit of electric resistance?",
    options: ["Ampere", "Volt", "Ohm", "Watt"],
    correctIndex: 2,
    explanation: "Ohm (Ω) is the SI unit of electrical resistance.",
  },
  {
    id: "q-sci-6",
    category: "Science",
    difficulty: "Easy",
    question: "Which process do green plants use to synthesize food from sunlight?",
    options: ["Respiration", "Photosynthesis", "Transpiration", "Osmosis"],
    correctIndex: 1,
    explanation: "Photosynthesis uses light energy to convert CO₂ and water into glucose and oxygen.",
  },
  {
    id: "q-sci-7",
    category: "Science",
    difficulty: "Medium",
    question: "What acceleration due to gravity (g) is near Earth's surface?",
    options: ["5.8 m/s²", "9.8 m/s²", "12.4 m/s²", "15.0 m/s²"],
    correctIndex: 1,
    explanation: "Standard acceleration due to Earth's gravity is approximately 9.8 m/s².",
  },
  {
    id: "q-sci-8",
    category: "Science",
    difficulty: "Hard",
    question: "Which acid is present in human gastric juice in stomach?",
    options: ["Sulfuric Acid", "Nitric Acid", "Hydrochloric Acid", "Acetic Acid"],
    correctIndex: 2,
    explanation: "Hydrochloric acid (HCl) in gastric juice helps digest food and kill bacteria.",
  },
  {
    id: "q-sci-9",
    category: "Science",
    difficulty: "Medium",
    question: "Which gas is most abundant in Earth's atmosphere?",
    options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Argon"],
    correctIndex: 2,
    explanation: "Nitrogen makes up roughly 78% of Earth's atmosphere.",
  },
  {
    id: "q-sci-10",
    category: "Science",
    difficulty: "Hard",
    question: "What law states that energy cannot be created or destroyed?",
    options: [
      "Boyle's Law",
      "Law of Conservation of Energy",
      "Newton's Second Law",
      "Hooke's Law",
    ],
    correctIndex: 1,
    explanation: "The Law of Conservation of Energy states energy can only be transformed from one form to another.",
  },

  // English (10)
  {
    id: "q-eng-1",
    category: "English",
    difficulty: "Easy",
    question: "What is a synonym for 'Meticulous'?",
    options: ["Careless", "Careful", "Hurried", "Lazy"],
    correctIndex: 1,
    explanation: "'Meticulous' means showing great attention to detail, very careful.",
  },
  {
    id: "q-eng-2",
    category: "English",
    difficulty: "Easy",
    question: "Choose the correct antonym for 'Transparent':",
    options: ["Clear", "Opaque", "Bright", "Translucent"],
    correctIndex: 1,
    explanation: "'Opaque' means not transparent, not allowing light to pass through.",
  },
  {
    id: "q-eng-3",
    category: "English",
    difficulty: "Medium",
    question: "Identify the figure of speech: 'The wind whispered through the trees.'",
    options: ["Simile", "Metaphor", "Personification", "Hyperbole"],
    correctIndex: 2,
    explanation: "Giving human qualities ('whispered') to non-human elements ('wind') is personification.",
  },
  {
    id: "q-eng-4",
    category: "English",
    difficulty: "Medium",
    question: "Fill in the blank: 'Neither he nor his friends ____ present.'",
    options: ["is", "were", "was", "be"],
    correctIndex: 1,
    explanation: "With 'neither... nor', the verb agrees with the subject closest to it ('his friends' -> 'were').",
  },
  {
    id: "q-eng-5",
    category: "English",
    difficulty: "Hard",
    question: "What does the idiom 'Bite the bullet' mean?",
    options: [
      "To eat quickly",
      "To face a difficult situation with courage",
      "To start a fight",
      "To make a silly mistake",
    ],
    correctIndex: 1,
    explanation: "'Bite the bullet' means to endure a painful or difficult situation bravely.",
  },
  {
    id: "q-eng-6",
    category: "English",
    difficulty: "Easy",
    question: "Which of the following is a noun?",
    options: ["Quickly", "Happiness", "Beautiful", "Run"],
    correctIndex: 1,
    explanation: "'Happiness' is an abstract noun.",
  },
  {
    id: "q-eng-7",
    category: "English",
    difficulty: "Medium",
    question: "Choose the correct spelling:",
    options: ["Accommodate", "Acommodate", "Accomodate", "Acomodate"],
    correctIndex: 0,
    explanation: "'Accommodate' has double 'c' and double 'm'.",
  },
  {
    id: "q-eng-8",
    category: "English",
    difficulty: "Hard",
    question: "Identify the clause type: 'Although it was raining, we went for a walk.'",
    options: ["Adverbial Clause", "Noun Clause", "Adjective Clause", "Prepositional Phrase"],
    correctIndex: 0,
    explanation: "'Although it was raining' is a subordinate adverbial clause of concession.",
  },
  {
    id: "q-eng-9",
    category: "English",
    difficulty: "Medium",
    question: "What is the past participle of the verb 'Write'?",
    options: ["Wrote", "Writing", "Written", "Writes"],
    correctIndex: 2,
    explanation: "Write (present), wrote (past), written (past participle).",
  },
  {
    id: "q-eng-10",
    category: "English",
    difficulty: "Hard",
    question: "What is a 'portmanteau' word?",
    options: [
      "A word borrowed from Ancient Greek",
      "A word combining the sounds and meanings of two words",
      "A word that sounds like what it describes",
      "A word that is its own opposite",
    ],
    correctIndex: 1,
    explanation: "A portmanteau blends two words together (e.g. Smoke + Fog = Smog).",
  },

  // Social Studies (10)
  {
    id: "q-soc-1",
    category: "Social Studies",
    difficulty: "Easy",
    question: "Which line of latitude divides the Earth into Northern and Southern Hemispheres?",
    options: ["Tropic of Cancer", "Prime Meridian", "Equator", "Tropic of Capricorn"],
    correctIndex: 2,
    explanation: "The Equator at 0° latitude divides Earth into Northern and Southern Hemispheres.",
  },
  {
    id: "q-soc-2",
    category: "Social Studies",
    difficulty: "Easy",
    question: "Who is known as the Father of the Indian Constitution?",
    options: [
      "Mahatma Gandhi",
      "Dr. B.R. Ambedkar",
      "Jawaharlal Nehru",
      "Sardar Vallabhbhai Patel",
    ],
    correctIndex: 1,
    explanation: "Dr. B.R. Ambedkar was the Chairman of the Drafting Committee of the Indian Constitution.",
  },
  {
    id: "q-soc-3",
    category: "Social Studies",
    difficulty: "Medium",
    question: "In which year did the Dandi March (Salt Satyagraha) take place?",
    options: ["1920", "1930", "1942", "1947"],
    correctIndex: 1,
    explanation: "Mahatma Gandhi led the Dandi March in March-April 1930.",
  },
  {
    id: "q-soc-4",
    category: "Social Studies",
    difficulty: "Medium",
    question: "Which river is known as the longest river in the world?",
    options: ["Amazon River", "Nile River", "Yangtze River", "Mississippi River"],
    correctIndex: 1,
    explanation: "The Nile River in Africa is traditionally recognized as the longest river.",
  },
  {
    id: "q-soc-5",
    category: "Social Studies",
    difficulty: "Hard",
    question: "Which organ of the United Nations is responsible for maintaining international peace and security?",
    options: [
      "General Assembly",
      "Security Council",
      "International Court of Justice",
      "Economic and Social Council",
    ],
    correctIndex: 1,
    explanation: "The UN Security Council has primary responsibility for international peace and security.",
  },
  {
    id: "q-soc-6",
    category: "Social Studies",
    difficulty: "Easy",
    question: "What is the capital city of Karnataka?",
    options: ["Mysuru", "Bengaluru", "Hubballi", "Mangaluru"],
    correctIndex: 1,
    explanation: "Bengaluru is the capital city of Karnataka state.",
  },
  {
    id: "q-soc-7",
    category: "Social Studies",
    difficulty: "Medium",
    question: "The Industrial Revolution first originated in which country during 18th century?",
    options: ["France", "Germany", "Great Britain", "United States"],
    correctIndex: 2,
    explanation: "The Industrial Revolution began in Great Britain in the mid-18th century.",
  },
  {
    id: "q-soc-8",
    category: "Social Studies",
    difficulty: "Hard",
    question: "Which fundamental right in the Indian Constitution is referred to as the 'Heart and Soul' by Dr. Ambedkar?",
    options: [
      "Right to Equality",
      "Right to Freedom",
      "Right to Constitutional Remedies",
      "Right against Exploitation",
    ],
    correctIndex: 2,
    explanation: "Article 32 (Right to Constitutional Remedies) was called the Heart and Soul of the Constitution.",
  },
  {
    id: "q-soc-9",
    category: "Social Studies",
    difficulty: "Medium",
    question: "What type of soil is also known as 'Regur Soil'?",
    options: ["Alluvial Soil", "Red Soil", "Black Soil", "Laterite Soil"],
    correctIndex: 2,
    explanation: "Black soil is widely known as Regur soil and is ideal for cotton cultivation.",
  },
  {
    id: "q-soc-10",
    category: "Social Studies",
    difficulty: "Hard",
    question: "Which mountain range separates Europe from Asia?",
    options: ["Alps", "Ural Mountains", "Himalayas", "Rockies"],
    correctIndex: 1,
    explanation: "The Ural Mountains run north to south through Russia and separate Europe from Asia.",
  },

  // General Knowledge (10)
  {
    id: "q-gk-1",
    category: "General Knowledge",
    difficulty: "Easy",
    question: "Which planet is known as the Red Planet?",
    options: ["Venus", "Jupiter", "Mars", "Saturn"],
    correctIndex: 2,
    explanation: "Mars appears red due to iron oxide (rust) on its surface.",
  },
  {
    id: "q-gk-2",
    category: "General Knowledge",
    difficulty: "Easy",
    question: "How many sides does a Heptagon have?",
    options: ["6", "7", "8", "9"],
    correctIndex: 1,
    explanation: "A heptagon is a 7-sided polygon.",
  },
  {
    id: "q-gk-3",
    category: "General Knowledge",
    difficulty: "Medium",
    question: "In which year did the First World War begin?",
    options: ["1912", "1914", "1918", "1939"],
    correctIndex: 1,
    explanation: "World War I began on July 28, 1914.",
  },
  {
    id: "q-gk-4",
    category: "General Knowledge",
    difficulty: "Medium",
    question: "Who painted the Mona Lisa?",
    options: [
      "Vincent van Gogh",
      "Pablo Picasso",
      "Leonardo da Vinci",
      "Michelangelo",
    ],
    correctIndex: 2,
    explanation: "Leonardo da Vinci painted the Mona Lisa in the early 16th century.",
  },
  {
    id: "q-gk-5",
    category: "General Knowledge",
    difficulty: "Hard",
    question: "Which chemical element has the highest thermal conductivity of any natural material?",
    options: ["Gold", "Silver", "Diamond (Carbon)", "Copper"],
    correctIndex: 2,
    explanation: "Diamond (allotrope of Carbon) has the highest thermal conductivity.",
  },
  {
    id: "q-gk-6",
    category: "General Knowledge",
    difficulty: "Easy",
    question: "What is the national animal of India?",
    options: ["Elephant", "Royal Bengal Tiger", "Lion", "Leopard"],
    correctIndex: 1,
    explanation: "The Royal Bengal Tiger is the national animal of India.",
  },
  {
    id: "q-gk-7",
    category: "General Knowledge",
    difficulty: "Medium",
    question: "Which island nation is the world's largest archipelagic state?",
    options: ["Philippines", "Japan", "Indonesia", "Maldives"],
    correctIndex: 2,
    explanation: "Indonesia consists of over 17,000 islands, making it the largest archipelagic state.",
  },
  {
    id: "q-gk-8",
    category: "General Knowledge",
    difficulty: "Hard",
    question: "Who developed the World Wide Web (WWW) in 1989?",
    options: ["Steve Jobs", "Tim Berners-Lee", "Bill Gates", "Alan Turing"],
    correctIndex: 1,
    explanation: "Tim Berners-Lee invented the World Wide Web while working at CERN.",
  },
  {
    id: "q-gk-9",
    category: "General Knowledge",
    difficulty: "Medium",
    question: "Which instrument is used to measure atmospheric pressure?",
    options: ["Thermometer", "Barometer", "Hygrometer", "Anemometer"],
    correctIndex: 1,
    explanation: "A barometer measures atmospheric pressure.",
  },
  {
    id: "q-gk-10",
    category: "General Knowledge",
    difficulty: "Hard",
    question: "What is the official currency of Japan?",
    options: ["Yuan", "Won", "Yen", "Baht"],
    correctIndex: 2,
    explanation: "The Japanese Yen (¥) is the official currency of Japan.",
  },
];
